### ISSUE TITLE
What's the background technology behind `<browser>.addEventListener 'keydown'`

### ISSUE THREAD

**Issue by gdh1995** [lydell/webextension-keyboard#4]
I'm very curious about current implementation of `<browser>.addEventListener` in a multi-process version of FireFox. As far as I know, FireFox is able to use a shim called CPOW to provide `contentDocument` (if `em:multiprocessCompatible` is false), but the "keydown" listener still works even when multiprocessCompatible is enabled.

Here's my tests using VimFx's newest code on FireFox nightly (ver 53).

### 1. `multiprocessCompatible` disabled
* a `keydown` event in `extension/lib/events.coffee` has a `target` of `<tabbrowser#content>`
* `event.composedTarget` and `event.originalTarget` is a same `<xul:browser>`
* I could not find any access from a `KeyboardEvent` to DOM nodes of the page content.
* `@window` at line 81 is a `ChromeWindow → chrome://browser/content/browser.xul`
* `event.view` is the same as `@window`
* `@window.gBrowser.contentDocument.children[0].children` returns `[<head>, <body>]`

### 2. `multiprocessCompatible` enabled

* a `keydown` event in `events.coffee` has also a `target` of `<tabbrowser#content>`
* its `composedTarget` and `originalTarget` is also a same `<xul:browser>`
* `event.view` is `@window`, a `ChromeWindow → chrome://browser/content/browser.xul`
* could not find any access to DOM nodes, either
* `@.window.gBrowser.contentDocument` is `null`

It seems that `multiprocessCompatible: true` does disable shims in https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts#Compatibility_shims, but the `https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts#Without_the_shim_3` says:
> It used to be that if you registered a listener on the XUL <browser>  or <tab> element that hosted some DOM content, then events in the content would bubble up to the XUL and you could handle them there. This no longer happens in multiprocess Firefox.

I **don't understand what happens**. `VimFx` does install many event listeners on `@window` (`<browser>`) and they all works well.

In my knowledge, the content process is in charge of receiving and handling messages from the operating system, so **will a content firstly and  synchronously pass those messages to the Chrome (UI) process and then handle them by itself**? Seems too strange.

@lydell Thanks for your patience at the last issue. This issue may be exactly where I'm wrong and I'm expecting your answer.

**Comment by lydell** [comment]
Your research seems to be correct. I don’t really understand what your question is, though :)

**Comment by gdh1995** [comment]
I think it's just another shim which enables background/main scripts to block such events, and I guess it is "sendSyncMessage".

But its cost shouldn't have been small enough that it's been ignored by "multiprocessCompatible"...

Should it? Would Firefox remove such a sync function when WebExtension APIs are prepared?

**Comment by lydell** [comment]
Perhaps this helps.

1. The user presses a key on the keyboard.
2. The operating system receives the key, and then passes it to the currently focused program, in this case Firefox.
3. Firefox receives the key, in the main process. In any of the steps below, event listeners can cancel the event (via `event.preventDefault()` and `event.stopPropagation()`).
   1. A 'keydown' event goes down Firefox's tree of UI elements (capture phase).
   2. If the `<browser>` element of the current tab is focused, the following steps happen, otherwise this step is skipped.
      1. Firefox's main process passes the key to the web page, and waits (non-blocking) for the web page to return.
      2. The web page receives the key, and goes down the tree of web page elements (capture phase).
      3. The key bubbles up the tree of web page elements (bubble phase).
   3. The 'keydown' event bubbles up in Firefox's tree of UI elements (bubble phase).
4. Handling of the key is done.

**Comment by gdh1995** [comment]
Maybe. And if so then "onKey" will be perfect.

It's beyond my imagination to receive system mrssages via the main (UI/Chrome) process.

Anyway, it's time to close this issue.

**Comment by gdh1995** [comment]
> A 'keydown' event goes down Firefox's tree of UI elements (capture phase).

I've used `Process Explorer` to confirmed this, and Chrome just does the same. But I gets a new point to discuss:
* Nowadays, Firefox runs addons like `VimFx` just in its UI (Chrome) process, and allows `VimFx` to block keyboard events;
* But we know that Chrome creates a new background process for each persistent extension;
* Then, it will be harder and more expensive to implement such a blocking functionality on the WebExtension framework.

So the keypoint is: will Firefox split its addon environments into different processes?

**Comment by lydell** [comment]
> Then, it will be harder and more expensive to implement such a blocking functionality on the WebExtension framework.

Why? That's no worse than allowing web pages to call `event.preventDefault()`, is it?

> So the keypoint is: will Firefox split its addon environments into different processes?

Why is that a key point?

**Comment by gdh1995** [comment]
Now Firefox only use two processes to handle key events:
* Chrome process/native code ---(in the same process)--> Chrome process/Addon listeners ---(across process)--> Content process/page listeners

and each step may `preventDefault` the process.

But for Chrome, extensions are in other processes, so I think with the new WebExtension framework, it might be:
* UI process ---(across process)--> extension background ---(across process)-->UI process get response
 ---(across process)--> Content process/page listeners

More expensive, isn't it?

**Comment by lydell** [comment]
Yes, it sounds more expensive. I now see your point – we’re trying to guess what Firefox and Chrome developers might object to in this proposal. Good to think about.
